### ISSUE TITLE
some questions about paladin

### ISSUE THREAD

**Issue by qahehe** [pkuoslab/Paladin#2]
你好，我刚读完你们的文章，我有个问题想问一下你们。

1 这篇文章的目标是实现可重复测试的自动化用例生成。 但是产生的test case 在哪里？
/output file 仅仅含有一个path的json 文件还有一个screenshot，这种输出怎么运用到自动化测试里，
能检测出多少错误？

2 我的想法是paladin 在一个应用里run 15分钟，生成测试用例，然后用这个生成的path json去进行对其他安卓版本或app进行测试。主要就是通过adb command 去触发控件和 GUI VIEW TREE的构建的测试？

**Comment by Mike-Huang01** [comment]
Test case并没有显示地存储到文件中，json文件存储的是app的状态图，根据指定的某一个状态，paladin会搜索出一条能抵达该状态的路径，这条路径就是test case。

当然你也可以自己加载该状态图，预先把所有节点的路径都存储起来作为test case的集合，不过由于app的状态经常会发生微小的扰动，直接使用adb command触发控件执行test case效果可能并不好。
